services:
  - name: e2ee-chatapp
    type: web
    env: python
    plan: free  # Using Render's free plan
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    envVars:
      - key: SECRET_KEY
        value: your-secret-key
    regions:
      - oregon
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true  # Automatically generates a secret key
      - key: DEBUG
        value: "False"  # Set to "True" only for debugging in development
