# Generated by Django 5.1.4 on 2025-04-11 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('user_name', models.CharField(default='Anonymous', max_length=255)),
                ('email', models.EmailField(blank=True, help_text='Optional. Only if you want a response.', max_length=254, null=True)),
                ('message', models.TextField()),
                ('subscribed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extraData', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
