# Generated by Django 5.1.4 on 2025-04-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='extraData',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(blank=True, help_text='Optional. Only if you want a response.', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user_name',
            field=models.CharField(default='Anonymous', max_length=255),
        ),
    ]
