# Generated by Django 5.1.4 on 2026-08-25 14:11

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_add_receiver_index_and_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='prefetchlink',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 8, 25, 14, 11, 55, 550224, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
