# Generated by Django 5.1.4 on 2025-02-28 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_message_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='recipient',
            new_name='recipient_id',
        ),
    ]
