# Generated by Django 5.1.4 on 2025-03-02 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_rename_recipient_message_recipient_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='recipient_id',
        ),
        migrations.AddField(
            model_name='message',
            name='msg_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='receiver_id',
            field=models.UUIDField(default='bibidibobidiboo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='encrypted_message',
            field=models.JSONField(),
        ),
    ]
