# Generated by Django 5.1.4 on 2025-03-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_remove_message_recipient_id_message_msg_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dp',
            field=models.TextField(blank=True, null=True),
        ),
    ]
