# Generated by Django 5.1.4 on 2025-03-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_user_dp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='file',
        ),
        migrations.AddField(
            model_name='media',
            name='filePath',
            field=models.TextField(default='unknown_bihh'),
            preserve_default=False,
        ),
    ]
