# Generated by Django 5.1.4 on 2025-04-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_remove_media_file_media_filepath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default="Heyy👋, I'm new on this app"),
        ),
    ]
